name: CI_CD_pipeline
env:
   EB_PACKAGE_S3_BUCKET_NAME : "sleepdeployrepeat"
   EB_APPLICATION_NAME       : "flask_app"
   EB_ENVIRONMENT_NAME       : "Flaskapp-env"
   DEPLOY_PACKAGE_NAME       : "flask_app.zip"
   AWS_REGION_NAME           : "eu-north-1"


on:
  push:
    branches:
      - main 

jobs:
  CI_part:
    runs-on: ubuntu-latest

    steps:
      - name: Clone our repository
        uses: actions/checkout@v1
      
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git* 

      - name: Configure AWS authentication
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id     :   ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key :   ${{ secrets.AWS_SECRET_KEY }}
          aws-region            :   ${{ env.AWS_REGION_NAME }}
          
      - name: Copy deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name: Final message
        run : echo "CI part finished successfully"
